version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: new_employee_db
    ports:
      - "6025:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: new_employee_db
      DB_PASSWORD: admin123
      DB_PORT: 5432
      JWT_SECRET: Abderoiouwi@12342
      NODE_ENV: development

  dashboard:
    build:
      context: ./Frontend/dashboard
    container_name: dashboard
    ports:
      - "9025:80"

  forgot:
    build:
      context: ./Frontend/forgot
    container_name: forgot
    ports:
      - "9026:80"

  login:
    build:
      context: ./Frontend/login
    container_name: login
    ports:
      - "9027:80"

  signup:
    build:
      context: ./Frontend/signup
    container_name: signup
    ports:
      - "9028:80"

volumes:
  pgdata:

